jira:
  image: cptactionhank/atlassian-jira:7.0.5
  ports:
    - 8080:8080
  container_name: jira
  links:
    - jira-db

jira-db:
  image: postgres
  container_name: jira-db

confluence:
  image: cptactionhank/atlassian-confluence:5.9.2
  ports:
    - 8090:8090
  container_name: confluence
  links:
    - confluence-db

confluence-db:
  image: postgres
  container_name: confluence-db
