jira:
  build: ./jira
  ports:
    - 8080:8080
  container_name: jira

jira-db:
  image: postgres
  container_name: jira-db

confluence:
  build: ./confluence
  ports:
    - 8090:8090
  container_name: confluence

confluence-db:
  image: postgres
  container_name: confluence-db
