proxy:
  build: ./proxy
  ports:
    - 8080:8080
  container_name: proxy

jira:
  build: ./jira
  container_name: jira

jira-db:
  image: postgres
  container_name: jira-db

confluence:
  build: ./confluence
  container_name: confluence

confluence-db:
  image: postgres
  container_name: confluence-db
